### ISSUE TITLE
如何学习tf源码

### ISSUE THREAD

**Issue by bringtree** [facaiy/book_notes#20]
大佬 你好
我用TensorFlow 也有一段时间了。先阶段想了解tf的源码。
我下知道请教下大佬是如何渐进式学习 TensorFlow源码的？
我看大佬提交过好多次pr了
大佬 有什么学习资源可以分享一下吗？
我网上找了一些文章看后还是一头雾水，不知道如何下手，搞不清哪些是优先级比较高的重点 哪些可以暂时忽略。想知道 大佬在刚开始接触tf的时候是怎么做的？
0000rz
或者有遇到过什么比较大的困难 和弯路可以讲一讲吗？

**Comment by facaiy** [comment]
你好，@bringtree . 
我只是个普通的开发者，接触TensorFlow时间其实并不长，大概三个月，所以不敢妄称擅长。
你可以考虑从较为简单的BUG修复开始，先在Python侧做些尝试，然后再逐渐进入到C侧。尽量先集中在一个模块，关注相关的issue，慢慢就会增多了解。
希望对你有用，加油。
